### ISSUE TITLE
RAM Error

### ISSUE THREAD

**Issue by vipermark7** [graphitemaster/moreram#3]
I tried to use this and I think my RAM must have had a integer overflow. I now have -256GB RAM. pls send heERROR #X09AB COMPUTER HAS RUN OUT OF RAM

**Comment by Rickgg** [comment]
Did you read the whole README? If not, PLEASE do.

**Comment by vipermark7** [comment]
I did, in fact. I was just messing around haha

**Comment by graphitemaster** [comment]
moreram does not support negative memories yet, something about the compiler incapable of producing negative sized shared object files is really holding this feature back. Consider opening a ticket against your compiler vendor regarding this issue.
