### ISSUE TITLE
Input parameter validation for function "free"?

### ISSUE THREAD

**Issue by elfring** [graphitemaster/moreram#5]
Should the parameter "address" be checked [if it is eventually a null pointer before further actions will be performed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html) by [your implementation of the function "free"](https://github.com/graphitemaster/moreram/blob/789e1521ea0114b3a9aa1c46f2a071706565b2e7/moreram.c#L232)?

**Comment by graphitemaster** [comment]
Nice catch, fixed

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/graphitemaster/moreram/commit/ca7001dae7d52be240dc5e41d7a728b3acce7724).
